name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SCons
      run: sudo apt-get install -y scons

    - name: Install Doctest
      run: |
	git clone https://github.com/onqtam/doctest.git $HOME/doctest
	export DOCTEST_HOME=$HOME/doctest

    - name: Build project
      run: scons

    - name: Run unit tests
      run: ./test_parser
      env:
	DOCTEST_HOME: $HOME/doctest
